### ISSUE TITLE
Temperature is inverted

### ISSUE THREAD

**Issue by ubald** [waxlamp/elgato#18]
Hi, small issue with warmer/cooler temperature control. 

https://github.com/waxlamp/elgato/blob/2c8b30047eda472dae0db966f12fb0a11b74e966/elgato/__main__.py#L193-L196

The lowest end of the range is the warm range even though they show it the other way around in the UI. So it should do +500 for cooler and -500 for warmer.

Otherwise, excellent job on the script. Configured with keyboard shortcuts, this is even better than the original UI.

**Comment by waxlamp** [comment]
Thank you for the kind words about the project!

And, thank you also for finally resolving a confusion I must have held for a long time. Indeed, according to [wikipedia](https://en.wikipedia.org/wiki/Color_temperature):

> Color temperatures over 5000 K are called "cool colors" (bluish), while lower color temperatures (2700–3000 K) are called "warm colors" (yellowish). "Warm" in this context is an analogy to radiated heat flux of traditional incandescent lighting rather than temperature. The spectral peak of warm-coloured light is closer to infrared, and most natural warm-coloured light sources emit significant infrared radiation. The fact that "warm" lighting in this sense actually has a "cooler" color temperature often leads to confusion.

Thanks for pointing this out, and please try out the fix in #19 to see if I got it right. If so, I'll cut a new release of the package.
